-- TURN OFF SECURITY LOCKS TEMPORARILY
ALTER TABLE "public"."orders" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."order_items" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."addresses" DISABLE ROW LEVEL SECURITY;
